version: "3.9"
services:
  postgres_new_life:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "new_life"
      POSTGRES_USER: "vladimir_leontev"
      POSTGRES_PASSWORD: "hbuwedi8#1!du723481d"
    volumes:
      - postgres_new_life_volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_new_life_volume:
    driver: local
    driver_opts:
      type: none
      device: ./.data
      o: bind
